### ISSUE TITLE
Consider supporting expiration

### ISSUE THREAD

**Issue by zonyitoo** [edward-shen/lfu-cache#1]
https://github.com/maidsafe/lru_time_cache

In cache use cases, we not only want to eliminate keys by LFU to keep the cache size, but also require to set expire time.

An easy solution is to add another binary tree of `Node`s as a binary heap.

**Comment by edward-shen** [comment]
Thanks for the suggestion.

Seems reasonable, but it would have to be a different struct `LfuTimeCache` as that would bound insertions to O(log n) instead of O(1).

I'll get to implementing this eventually, or a PR would also be gladly appreciated.

**Comment by zonyitoo** [comment]
I would recommend to add methods like `insert_with_expiry` to the current `LfuCache`. The LFU part of `LfuTimeCache` should be exactly the same as `LfuCache`, which will increase maintainance cost.

**Comment by edward-shen** [comment]
I consider asymptotic time complexity as part of the public API, so changing LfuCache would necessary require a `2.0.0` for this feature. I don't think a 2.0.0 this early in the crate's lifetime would be a good idea.

That being said, the objective of the current LfuCache was so that it should be highly composable to add additional eviction conditions without too much of a maintenance cost.

It looks to me that the implementation you provided performs a time-based eviction check on insert and on... mutable retrieval? Not quite too sure what's going on there, but since it looks like time-based eviction is effectively a wrapper around the standard eviction process, it should be a simple thing to add.

**Comment by zonyitoo** [comment]
> It looks to me that the implementation you provided performs a time-based eviction check on insert and on... mutable retrieval?

Yes, expire time will be updated on `insert`, `get`, `get_mut`, not only mutable retrieval.

I was trying to add this feature into `LfuCache` but I found that it is not an easy task, because the `FrequencyList` is now think it is the only owner of the `Node`. To implement this feature, I think the `lookup` hash map should be the owner of `Node` and `FrequencyList` and `ExpiryHeap` have mutable references of it.

 😅 It requires massive changes to the current code, which is why I open an issue instead of a PR.

I could make a PR after we have settle the core implementation design.

**Comment by edward-shen** [comment]
The problem with moving ownership to the HashMap is that the HashMap can and will move elements around in memory, which means that any points referring to it will need some form of indirection, e.g. through an Rc.

This is why the current implementation is the other way around, where the frequency list controls (saying that it "owns" would be confusing) where the memory location of the entry is.

Additionally, this also follows the referenced paper closer, as the lookup table is auxiliary to the frequency list.

---

That being said, I am trying something out. I think I can have a timed LFU cache that operates in O(log n) time for all operations, which would on par with the linked implementation.

**Comment by edward-shen** [comment]
Sorry for the late response, try out the new `TimedLfuCache` implementation and let me if that works.

**Comment by zonyitoo** [comment]
Excellent!! I will try that later.

**Comment by zonyitoo** [comment]
It would be better to have an `fn entry(&mut self)` method just like the containers in libstd.

Not an urgent request. It is just better to have one.
